config:
  clients:
    - url: http://loki-gateway.monitoring.svc:80/loki/api/v1/push

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

serviceMonitor:
  enabled: true

tolerations:
  - effect: NoSchedule
    operator: Exists
