{
 "title": "Kubernetes / Overview",
 "description": "This dashboard is designed to be a one-stop solution for monitoring your Kubernetes cluster",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DATASOURCE", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Cluster Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
     "options": {
      "content": "<div style=\"\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  background-color: #2f2f2f; /* Dark grey background */\n  color: white; /* White text */\n  height: 100%;\n  text-align: center;\n  border-radius: 8px; /* Optional: Rounded corners for better aesthetics */\n  font-family: 'Arial', sans-serif; /* Optional: Clean font for readability */\n  padding: 20px;\n\">\n  <h1>API Server</h1>\n</div>\n"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 20, "x": 4, "y": 1 },
     "options": {
      "content": "<div style=\"\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  background-color: #2f2f2f; /* Dark grey background */\n  color: white; /* White text */\n  height: 100%;\n  text-align: center;\n  border-radius: 8px; /* Optional: Rounded corners for better aesthetics */\n  font-family: 'Arial', sans-serif; /* Optional: Clean font for readability */\n  padding: 20px;\n\">\n  <h1>Nodes</h1>\n</div>\n"
     }
    },
    {
     "title": "Control Plane Status",
     "type": "stat",
     "description": "Indicates whether API Server, Scheduler or Controller manager is down.",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(up{job=~\"apiserver|kube-scheduler|kube-controller-manager\"} == 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Node Unschedulable",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_spec_unschedulable)"
      }
     ]
    },
    {
     "title": "Memory Pressure",
     "type": "stat",
     "description": "This is true if there is insufficient memory on the node, which could cause the node to swap frequently.",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\", status!=\"false\"})"
      }
     ]
    },
    {
     "title": "Disk Pressure",
     "type": "stat",
     "description": "This condition is true if there is insufficient disk space on the node.",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\", status!=\"false\"})"
      }
     ]
    },
    {
     "title": "PID Pressure",
     "type": "stat",
     "description": "True when there are too many processes running on the node, indicating a potential exhaustion of process identifiers (PIDs).",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"PIDPressure\", status!=\"false\"})"
      }
     ]
    },
    {
     "title": "Network Unavailable",
     "type": "stat",
     "description": "Indicates that the network to the node is not correctly configured or not available.",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"NetworkUnavailable\", status!=\"false\"})"
      }
     ]
    },
    {
     "title": "Node Not Ready",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"Ready\",status!=\"true\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 7 },
     "options": {
      "content": "<div style=\"\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  background-color: #2f2f2f; /* Dark grey background */\n  color: white; /* White text */\n  height: 100%;\n  text-align: center;\n  border-radius: 8px; /* Optional: Rounded corners for better aesthetics */\n  font-family: 'Arial', sans-serif; /* Optional: Clean font for readability */\n  padding: 20px;\n\">\n  <h1>Pods</h1>\n</div>\n"
     }
    },
    {
     "title": "Failed Pods",
     "type": "stat",
     "description": "Last 15Min",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(kube_pod_status_phase{phase=\"Failed\"}[15m]))"
      }
     ]
    },
    {
     "title": "Failed Pods Reason",
     "type": "stat",
     "description": "Indicates that there are pods that were evicted",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(kube_pod_status_reason[15m])) by (reason)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Unscheduled Pods",
     "type": "stat",
     "description": "Last 15Min",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(kube_pod_status_scheduled{condition=\"false\"}[15m]))"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 17 },
     "options": {
      "content": "<div style=\"\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  background-color: #2f2f2f; /* Dark grey background */\n  color: white; /* White text */\n  height: 100%;\n  text-align: center;\n  border-radius: 8px; /* Optional: Rounded corners for better aesthetics */\n  font-family: 'Arial', sans-serif; /* Optional: Clean font for readability */\n  padding: 20px;\n\">\n  <h1>Containers</h1>\n</div>\n"
     }
    },
    {
     "title": "CrashLoopBackOff",
     "type": "stat",
     "description": "Last 15Min",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(kube_pod_container_status_waiting_reason{reason=\"CrashLoopBackOff\"}[15m]))"
      }
     ]
    },
    {
     "title": "ErrImagePull",
     "type": "stat",
     "description": "Last 15Min",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(kube_pod_container_status_waiting_reason{reason=\"ErrImagePull\"}[15m]))"
      }
     ]
    },
    {
     "title": "ImagePullBackOff",
     "type": "stat",
     "description": "Last 15Min",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(kube_pod_container_status_waiting_reason{reason=\"ImagePullBackOff\"}[15m]))"
      }
     ]
    },
    {
     "title": "OOM Killed Containers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\"} == 1"
      }
     ]
    },
    {
     "title": "Containers in CPU Throttling",
     "type": "stat",
     "description": "Last 15Min",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(sum(rate(container_cpu_cfs_throttled_seconds_total[15m])) by (pod) > 0)"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 23 },
     "options": {
      "content": "<div style=\"\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  background-color: #2f2f2f; /* Dark grey background */\n  color: white; /* White text */\n  height: 100%;\n  text-align: center;\n  border-radius: 8px; /* Optional: Rounded corners for better aesthetics */\n  font-family: 'Arial', sans-serif; /* Optional: Clean font for readability */\n  padding: 20px;\n\">\n  <h1>Persistent Volume Claims</h1>\n</div>\n"
     }
    },
    {
     "title": "PVCs Above 80%",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{} ) and (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{} )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{} )) >= (80 / 100)) or vector (0)"
      }
     ]
    },
    {
     "title": "PVCs in Lost State",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=\"Lost\"})"
      }
     ]
    }
   ]
  },
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 2 },
   "options": {
    "content": "<div style=\"\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  background-color: #2f2f2f; /* Dark grey background */\n  color: white; /* White text */\n  height: 100%;\n  text-align: center;\n  border-radius: 8px; /* Optional: Rounded corners for better aesthetics */\n  font-family: 'Arial', sans-serif; /* Optional: Clean font for readability */\n  padding: 20px;\n\">\n  <h1>Memory Information</h1>\n</div>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 2 },
   "options": {
    "content": "<div style=\"\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  background-color: #2f2f2f; /* Dark grey background */\n  color: white; /* White text */\n  height: 100%;\n  text-align: center;\n  border-radius: 8px; /* Optional: Rounded corners for better aesthetics */\n  font-family: 'Arial', sans-serif; /* Optional: Clean font for readability */\n  padding: 20px;\n\">\n  <h1>CPU Information</h1>\n</div>\n"
   }
  },
  {
   "title": "Node Memory Ratio",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\"}) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\"}) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\"}) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Node CPU Ratio",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{container!=\"\"}[2m])) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\"})",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\"}) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\"}) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Node Memory Information",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{container!=\"\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Node CPU Number of cores",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\"})",
     "legendFormat": "Total Cores"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{id=\"/\"}[2m]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{container!=\"\"})",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "CPU Used Cores",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\"})",
     "legendFormat": "Total Cores"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{id=\"/\"}[2m]))",
     "legendFormat": "Usage"
    }
   ]
  },
  { "title": "Cluster Resource Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 },
   "repeat": "origin_prometheus",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count({__name__=~\"kube_deployment_metadata_generation|kube_daemonset_metadata_generation|kube_statefulset_metadata_generation\",})",
     "legendFormat": "Workload"
    },
    { "expr": "count(kube_pod_info{})", "legendFormat": "Total Pod" },
    {
     "expr": "count by(key)(kube_node_spec_taint{key=~\"node.kubernetes.io.*\"})",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "count by(origin_prometheus)(kube_node_info{})",
     "legendFormat": "Total Nodes"
    },
    {
     "expr": "count by(origin_prometheus)(kube_node_info{}) - count by(origin_prometheus)(kube_node_spec_taint{key!~\"node.kubernetes.io.*\"})",
     "legendFormat": "Normal Node"
    },
    {
     "expr": "count by(key)(kube_node_spec_taint{key!~\"node.kubernetes.io.*\"})",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Kubernetes Resource Count - Total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(kube_pod_info{})", "legendFormat": "Running Pods" },
    { "expr": "sum(kube_service_info{})", "legendFormat": "Services" },
    { "expr": "sum(kube_ingress_info{})", "legendFormat": "Ingresses" },
    { "expr": "sum(kube_deployment_labels{})", "legendFormat": "Deployments" },
    { "expr": "sum(kube_statefulset_labels{})", "legendFormat": "Statefulsets" },
    { "expr": "sum(kube_daemonset_labels{})", "legendFormat": "Daemonsets" },
    {
     "expr": "sum(kube_persistentvolumeclaim_info{})",
     "legendFormat": "Persistent Volume Claims"
    },
    { "expr": "sum(kube_hpa_labels{})", "legendFormat": "Horizontal Pod Autoscalers" },
    { "expr": "sum(kube_configmap_info{})", "legendFormat": "Configmaps" },
    { "expr": "sum(kube_secret_info{})", "legendFormat": "Secrets" },
    {
     "expr": "sum(kube_networkpolicy_labels{})",
     "legendFormat": "Network Policies "
    }
   ]
  },
  {
   "title": "Kubernetes Pods QoS classes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_qos_class{}) by (qos_class)",
     "legendFormat": "{{ qos_class }} pods"
    },
    { "expr": "sum(kube_pod_info{})", "legendFormat": "Total pods" }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Health Status by Node",
   "type": "table",
   "description": "This table shows health status of nodes.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable) by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status!=\"true\"}) by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\", status!=\"false\"}) by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\", status!=\"false\"}) by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"PIDPressure\", status!=\"false\"}) by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"NetworkUnavailable\", status!=\"false\"}) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Statistic for node",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "kube_node_status_condition{status=\"true\"}  == 1",
     "legendFormat": "status"
    },
    {
     "expr": "kube_node_status_capacity{resource=\"cpu\"} - 0",
     "legendFormat": "node cpu capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (node)",
     "legendFormat": "pod cpu request total"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"}) by (node)",
     "legendFormat": "pod cpu limit total"
    },
    {
     "expr": "kube_node_status_capacity{resource=\"memory\"} - 0",
     "legendFormat": "node mem available total"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (node)",
     "legendFormat": "pod mem request total"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\"}) by (node)",
     "legendFormat": "pod mem limit total"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"})by (node) / sum(kube_node_status_capacity{resource=\"memory\"})by (node)",
     "legendFormat": "pod mem request %"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\"})by (node) / sum(kube_node_status_capacity{resource=\"memory\"})by (node)",
     "legendFormat": "pod mem limit %"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"})by (node) / sum(kube_node_status_allocatable{resource=\"cpu\"})by (node)",
     "legendFormat": "pod cpu request %"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"})by (node) / sum(kube_node_status_allocatable{resource=\"cpu\"})by (node)",
     "legendFormat": "pod cpu limit %"
    },
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\"})by (node) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\"})by (node)",
     "legendFormat": "container fs used %"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"pods\"})by (node)",
     "legendFormat": "node pod capacity"
    },
    {
     "expr": "count(kube_pod_info{created_by_kind!~\"<none>|Job\"}) by (node)",
     "legendFormat": "running pod"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{container!=\"\"}[2m])) by (node) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\"})by (node)*100 ",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container!=\"\"})by (node) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\"})by (node)*100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk by Mount Point",
   "type": "table",
   "description": "The table shows available disk size by mount points. Only mount point that used over 50% are displayed.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{fstype!=\"\"}) by (instance, fstype, mountpoint)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (instance, fstype, mountpoint) (node_filesystem_size_bytes{job=\"node-exporter\", fstype!=\"\", mountpoint!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Namespaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Pods Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "sum(kube_pod_owner{job=\"kube-state-metrics\"}) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(avg(namespace_workload_pod:kube_pod_owner:relabel{}) by (workload, namespace)) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Failed\"}) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Unknown\"}) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(avg_over_time(kube_pod_status_scheduled{condition=\"false\"}[5m])) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Information",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{}) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(namespace_cpu:kube_pod_container_resource_requests:sum{}) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{}) by (namespace) / sum(namespace_cpu:kube_pod_container_resource_requests:sum{}) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(namespace_cpu:kube_pod_container_resource_limits:sum{}) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{}) by (namespace) / sum(namespace_cpu:kube_pod_container_resource_limits:sum{}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Information",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\"}) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(namespace_memory:kube_pod_container_resource_requests:sum{}) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\"}) by (namespace) / sum(namespace_memory:kube_pod_container_resource_requests:sum{}) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(namespace_memory:kube_pod_container_resource_limits:sum{}) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\"}) by (namespace) / sum(namespace_memory:kube_pod_container_resource_limits:sum{}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workloads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Information",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "count(namespace_workload_pod:kube_pod_owner:relabel{}) by (workload, workload_type, namespace)"
      },
      {
       "expr": "sum(\n  node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{}\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{}\n) by (workload, workload_type)\n"
      },
      {
       "expr": "sum(\n  kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"cpu\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{}\n) by (workload, workload_type)\n"
      },
      {
       "expr": "sum(\n  node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{}\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{}\n) by (workload, workload_type, namespace)\n/sum(\n  kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"cpu\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{}\n) by (workload, workload_type, namespace)\n"
      },
      {
       "expr": "sum(\n  kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"cpu\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{}\n) by (workload, workload_type)\n"
      },
      {
       "expr": "sum(\n  node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{}\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{}\n) by (workload, workload_type)\n/sum(\n  kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"cpu\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{}\n) by (workload, workload_type)\n"
      }
     ]
    },
    {
     "title": "Memory Information",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "count(namespace_workload_pod:kube_pod_owner:relabel{}) by (workload, workload_type, namespace)"
      },
      {
       "expr": "sum(\n    container_memory_working_set_bytes{job=\"kubelet\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{}\n) by (workload, workload_type)\n"
      },
      {
       "expr": "sum(\n  kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"memory\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{}\n) by (workload, workload_type)\n"
      },
      {
       "expr": "sum(\n    container_memory_working_set_bytes{job=\"kubelet\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{}\n) by (workload, workload_type)\n/sum(\n  kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"memory\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{}\n) by (workload, workload_type)\n"
      },
      {
       "expr": "sum(\n  kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"memory\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{}\n) by (workload, workload_type)\n"
      },
      {
       "expr": "sum(\n    container_memory_working_set_bytes{job=\"kubelet\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{}\n) by (workload, workload_type)\n/sum(\n  kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"memory\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{}\n) by (workload, workload_type)\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jobs Succeeded",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_job_status_succeeded{})"
      }
     ]
    },
    {
     "title": "Last Succeeded Jobs",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 23 },
     "targets": [
      {
       "expr": "(time()-kube_job_status_completion_time{})/60/60/24>1",
       "legendFormat": "{{job_name}}"
      }
     ]
    },
    {
     "title": "Failed Jobs",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 23 },
     "targets": [
      { "expr": "kube_job_status_failed{}>=1", "legendFormat": "{{job_name}}" }
     ]
    },
    {
     "title": "Jobs Active",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(kube_job_status_active{})" }
     ]
    },
    {
     "title": "Jobs Failed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(kube_job_status_failed{})" }
     ]
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 },
     "options": {
      "content": "<div style=\"\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  background-color: #2f2f2f; /* Dark grey background */\n  color: white; /* White text */\n  height: 100%;\n  text-align: center;\n  border-radius: 8px; /* Optional: Rounded corners for better aesthetics */\n  font-family: 'Arial', sans-serif; /* Optional: Clean font for readability */\n  padding: 20px;\n\">\n  <h1>CPU Information</h1>\n</div>\n"
     }
    },
    {
     "title": "Top 10 CPU Consuming Pods",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, sum(rate(container_cpu_usage_seconds_total{container!=\"\"}[5m])) by (pod))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pod Containers CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max(irate(container_cpu_usage_seconds_total{container !=\"\",container!=\"POD\"}[2m])) by (container, pod, namespace) / (max(container_spec_cpu_quota{container !=\"\",container!=\"POD\"}/100000) by (container, pod, namespace)) * 100",
       "legendFormat": "{{ namespace }} / {{ pod }}"
      }
     ]
    },
    {
     "title": "CPU Throttling Seconds",
     "type": "timeseries",
     "description": "How many additional CPU was needed for container not to be in CPU Throttling",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{}[5m])) by (namespace,pod) > 0",
       "legendFormat": "{{namespace}} / {{pod}}"
      }
     ]
    },
    {
     "title": "CPU Usage vs Throttling Percent",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{}[1m])",
       "legendFormat": "CPU Cores Usage {{namespace}}/{{pod}}/{{container}}"
      },
      {
       "expr": "sum by (namespace,pod,container) ((container_cpu_cfs_throttled_periods_total{} / container_cpu_cfs_periods_total{}) * 100)",
       "legendFormat": "Throttle Percent {{namespace}}/{{pod}}/{{container}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 60 },
     "options": {
      "content": "<div style=\"\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  background-color: #2f2f2f; /* Dark grey background */\n  color: white; /* White text */\n  height: 100%;\n  text-align: center;\n  border-radius: 8px; /* Optional: Rounded corners for better aesthetics */\n  font-family: 'Arial', sans-serif; /* Optional: Clean font for readability */\n  padding: 20px;\n\">\n  <h1>Memory Information</h1>\n</div>\n"
     }
    },
    {
     "title": "Top 10 Memory Consuming Pods",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10,sum(container_memory_working_set_bytes{container!=\"\"}) by (pod))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pods with Potential Mem Leaks",
     "type": "timeseries",
     "description": "Pods whose Mem usage/Mem limits is more then 65%.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{container!=\"\"}) by (namespace,pod) /\r\nsum(kube_pod_container_resource_limits{resource=\"memory\"}) by (namespace,pod) > 0.65",
       "legendFormat": "{{ namespace }} / {{ pod }}"
      }
     ]
    },
    {
     "title": "Pod Container Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max (container_memory_working_set_bytes{container !=\"\",container!=\"POD\"}) by (namespace,container, pod)/ max(container_spec_memory_limit_bytes{container !=\"\",container!=\"POD\"}) by (namespace,container, pod) * 100",
       "legendFormat": "WSS：{{ namespace }} / {{ pod }}"
      },
      {
       "expr": "max (container_memory_rss{container !=\"\",container!=\"POD\"}) by (namespace,container, pod)/ max(container_spec_memory_limit_bytes{container !=\"\",container!=\"POD\"}) by (namespace,container, pod) * 100",
       "legendFormat": "RSS：{{ namespace }} / {{ pod }}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 94 },
     "options": {
      "content": "<div style=\"\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  background-color: #2f2f2f; /* Dark grey background */\n  color: white; /* White text */\n  height: 100%;\n  text-align: center;\n  border-radius: 8px; /* Optional: Rounded corners for better aesthetics */\n  font-family: 'Arial', sans-serif; /* Optional: Clean font for readability */\n  padding: 20px;\n\">\n  <h1>Events</h1>\n</div>\n"
     }
    },
    {
     "title": "Container Restarts",
     "type": "timeseries",
     "description": "Last 1h",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod, container) (increase(kube_pod_container_status_restarts_total{container!=\"\"}[1h])) > 1",
       "legendFormat": "{{ pod }} / {{ container }}"
      }
     ]
    },
    {
     "title": "OOM Events by Container",
     "type": "timeseries",
     "description": "Last 1h",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(container_oom_events_total{container!=\"\"}[1h])) by (pod, container) > 0",
       "legendFormat": "{{ pod }} / {{ container }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 122 },
   "collapsed": true,
   "panels": [
    {
     "title": "PVC Overview",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": " sum by (persistentvolumeclaim,namespace,storageclass,volumename) (kube_persistentvolumeclaim_info{})"
      },
      {
       "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{}/1024/1024/1024)"
      },
      {
       "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{}/1024/1024/1024)"
      },
      {
       "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_available_bytes{}/1024/1024/1024)"
      },
      {
       "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=~\"(Pending|Lost)\"}) by (persistentvolumeclaim) + sum(kube_persistentvolumeclaim_status_phase{phase=~\"(Lost)\"}) by (persistentvolumeclaim)"
      },
      {
       "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{}/kubelet_volume_stats_capacity_bytes{} * 100)"
      }
     ]
    },
    {
     "title": "All Running PVCs Used Bytes",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{}))",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    },
    {
     "title": "Daily Volume Use Rate (1D)",
     "type": "timeseries",
     "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(kubelet_volume_stats_used_bytes [1d])",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    }
   ]
  },
  {
   "title": "API Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 },
   "collapsed": true,
   "panels": [
    {
     "title": "Health Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"apiserver\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "API Server - Read Success Rate",
     "type": "stat",
     "description": "Last 5Min",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(apiserver_request_total{code=~\"20.*\",verb=~\"GET|LIST\"}[5m]))/sum(irate(apiserver_request_total{verb=~\"GET|LIST\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "API Server - Write Success Rate",
     "type": "stat",
     "description": "Last 5Min",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(apiserver_request_total{code=~\"20.*\",verb!~\"GET|LIST|WATCH|CONNECT\"}[5m]))/sum(irate(apiserver_request_total{verb!~\"GET|LIST|WATCH|CONNECT\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "API Server - CPU Usage in CPU Seconds",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=~\"kubernetes-apiservers|apiserver\"}[1m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Deprecated Kubernetes Resources",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "apiserver_requested_deprecated_apis",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "API Server - HTTP Requests Latency by instance",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_duration_seconds_sum{job=~\"kubernetes-apiservers|apiserver\"}[1m])) by (instance)\n/\nsum(rate(apiserver_request_duration_seconds_count{job=~\"kubernetes-apiservers|apiserver\"}[1m])) by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "API Server - Memory Usage by instance",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=~\"kubernetes-apiservers|apiserver\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "API Server - Errors by Instance",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(instance) (rate(apiserver_request_total{code=~\"5..\", job=~\"kubernetes-apiservers|apiserver\"}[1m]))",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "API Server - HTTP Requests Latency by verb",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_duration_seconds_sum{job=~\"kubernetes-apiservers|apiserver\"}[1m])) by (verb)\n/\nsum(rate(apiserver_request_duration_seconds_count{job=~\"kubernetes-apiservers|apiserver\"}[1m])) by (verb)",
       "legendFormat": "{{ verb }}"
      }
     ]
    },
    {
     "title": "Slowest Requests (Top 10) ",
     "type": "bargauge",
     "description": "Last 5Min",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, cluster_quantile:apiserver_request_duration_seconds:histogram_quantile{job=~\".+\",quantile=\"0.9\", subresource=\"\"})",
       "legendFormat": "{{resource}}:{{verb}}"
      }
     ]
    }
   ]
  }
 ]
}