apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-beta
  namespace: postgres
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5

  certificates:
    serverAltDNSNames:
      - "pg-beta.k8s.vicio.ovh"

  storage:
    storageClass: longhorn
    size: 10Gi

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi

  postgresql:
    parameters:
      shared_buffers: 128MB
      max_connections: "100"

  bootstrap:
    initdb:
      database: app
      owner: app
