---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgadmin-credentials
  namespace: postgres
spec:
  encryptedData:
    password: AgAhN8XtYcS/GV96YtsUukdAW2Jpr2eHr2qCEawqfQf4UA010ocs6ta4fHU0tXjJMJVnGg2eUhYw8OOuzh9pVBDLMItXDh5yfpMuw3ft+YQRgc7ZPPZUlJHpDgI6rAn2huA7m+1cSZU8LPm4ygxE22rp4Mzv4fDDGFxGdleV8Fvh17sZ9qcdEB8edgP0TdQYvSfIunKtnExNsV+23ASesHq3VtMrBfMR+Skbluwqy0PHYFB+S6fv8lTZNPzT1n5WQXFNJX/DLXJchfN3qehOYPn29YLWnWJxeWfuCZsiTPoGnfHT+H62QzLvFiKDq6XOgoGla/n/S1z8vtNFmon+3jNe7KfmwA3anSfBOALT9hNa6OklNhSCieCf6AJdWAa7N8mB7Nw+5YQjfJmfke2sK6cMW7aeDiXtOC+vV/kWPY/KD7Ddq33X8P5hlSlS1ywqgNy66DbZYgwX9EATrRyL7qfGodVotcx1j8ncnGVhnhNIn5C35rjsHPRzzhDaQBMn03SpXnvKP1hT0CT511OUg5kr/BGUsC1ZtFogYOStqYFRp2di2tzWGjhLR12/QampEU2NgyVZcvfIDzsP90RikbLnE044EjXD41wFXuswUiCFGbyTQDsvuuKGKjGoayqvAr/YZaUOcSEAIybtTdDDDOtS4qh768WNbRs4qhD/ZmYh+FUKdxEF0PWMKOARjqjUYLMZZbEnOIHUsWMci2utQTBcW6xo0A==
  template:
    metadata:
      name: pgadmin-credentials
      namespace: postgres
