apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: homeonly
  namespace: homepage
spec:
  ipAllowList:
    sourceRange:
      - 185.14.151.136/32
      - 87.205.23.9/32
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage
  namespace: homepage
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`home.k8s.vicio.ovh`)
      kind: Rule
      middlewares:
        - name: homeonly
      services:
        - name: homepage
          port: 80
  tls:
    secretName: wildcard-k8s-vicio-ovh-tls
