apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: mimir-distributed
      targetRevision: 5.5.0
      helm:
        releaseName: mimir
        valueFiles:
          - $values/k8s/apps/mimir/values.yaml
    - repoURL: https://github.com/wiktorkowalski/k8s-hetzner.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
