config:
  baseURL: ""
  oidc:
    secret:
      create: false
    externalSecret:
      enabled: true
      name: headlamp-oidc
    scopes: "openid profile email groups"
  extraArgs:
    - "-oidc-callback-url=https://headlamp.k8s.vicio.ovh/oidc-callback"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

serviceAccount:
  create: true
  name: headlamp

clusterRoleBinding:
  create: true

replicaCount: 1
