manager:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack

rbac:
  create: true

serviceAccount:
  create: true
  name: k6-operator

prometheusRule:
  enabled: true
  labels:
    release: kube-prometheus-stack

k6:
  image:
    repository: grafana/k6
    tag: latest
  extraArgs:
    - --out=experimental-prometheus-rw
    - --tag=testid={{ .TestRunID }}
  env:
    - name: K6_PROMETHEUS_RW_SERVER_URL
      value: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090/api/v1/write
    - name: K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM
      value: "true"
