apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-webhook
  namespace: monitoring
spec:
  encryptedData:
    url: AgCzqmlf5sugMQoT6QvILDPIkV4RsRm+A68jzD28+SDnkmM5v/2T5H4W4RLwMi6y3dewLEV//XjedWSIdh6MbIXALz7V6hKsUknHtfX1spwwKm25aRZbEAX3jdMpzRajreoPNyXr46TiyHlMSmQtHGnuR9096hJrYi+qn/X4h9zLnwL1mIoJKttoeW0PkL6uIaobb2JsZzQJUUtWxng+RuP2rNt91sGEwYa0qhvqhQ4MIv38gCFzTLSf32kLN2tbzf/LGQI0ALtODKM+ZkrDCgVlHIpGyWRljO29ZQrHadkXjyzIpQS5ra06HjHsT9RdwoDfTJwr7JKK88c8Zi2Uxwyg26EVtQ32gpmlTszZ5j6IoF66cJd0xsSKTP2q4GzJztuz0qywWVbQTomtGwK+ydqZZlvT4AfrzywTvW+9V0QZtWl+Bh9JwrdYnhy+TEfU0iHyVIblwwUila0Qj5wqd7v5jjJD6QkotWXP5J/H1jnOAq7+REedd6g78WVIu8XgU3xSC5UZE+NH6cqmX6/DTnAQCggDdrDSBZv6MU3BBz+tod1b6CZTI0J3bFN+uCY9hqTgSXx9RpoVqtHy7eQF2Wxp672A2mwZgQVb1PHcXX5qNy1mDIGCsyAQAv0q5BttGrN81A589reV0wn2Vfetb0cVaaNKX7lLu40VeII5S4smzs/0QNZ/NgMWVqa9WYsaZEtWKmi9W7Iqjlrr6h+R8+hD7u6LhXVYuoSARHUvXMj0scdlVFbqZeJUIhbW1ZR8fHwRl0fDFObJTR0zJ44C+EEAL5N9k9wazY3mLzkehGXrlt66rD8oWJqqzo4ooeVAK7oEGa5NXtRK8BabM47qHZhhLTYLS6gqEgjlm7CUkQh8
  template:
    metadata:
      name: discord-webhook
      namespace: monitoring
