apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBTzz5HmBPIkdi3Kb0fc1QlMn19qV6w3XCqhWc/ju8wf7vBCjxKckh5K361Bm9rFZCU1BbHlusdMNFE6RI+cI0WjAT+9xmKFgC/9/p7SQgMoYMUDMRrRjfUKZAh/IwaHTAENFN4n6ucfT+YDoPVlyPY8RQbrLDkSC5YpNsZCLEIvqsEM0FTrwT4ANKglV0vGb2/hDoCKaNGayuBOfTDcaImQg/QDocCtWV/XXQQtc3hSuCyh1RS9k1vscuAL9ogj2Bfw5e4/hTgwabj5yaePk05n3A8Vsro9WXqN+Zyda+U93Og/87VHsxpKA3eywpz1HgtJX29yDy8+dVg7XGVTSjCiAlFuOfxzdaOVgAKDKWKUD+ACK2X9+vppaBMS+Nl6CH/sFU2NVZYenAp7twTYz7Vw2TmtmQ88RLs7cJA5cQpV993aCyASqqY4VWGSZsLjZXnV7Yzrv6Oq9MLmxi5ldZXUZu/B+WgpGVT24r3y5zWMbgbfDil9QI6z/iJXiCbtb1IAjEndxGYP7RPp9Ajn5qx3wixtPR4J9RE+lCXLZfNXLBBEvsqeBE5uJ9eU0jF1O2DtQRYdlVcI9Qax4kQCReOJNQc2uTuJMk8TLdFnW1BuLRzvt/0IwFKdYkAgHsgUc68v0n0rVmwEcSQriXqB+/XukG8RMUdyT0ac7BBuEPhojFot0FIyi1ZnWmU8118+5CIa2mNKf7ZDK9ajdSzSHfv7UfD/1JlXNbnV5a4y1gZOZ/koqJNZj5V
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: wiktor9196667@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-k8s-vicio-ovh
  namespace: monitoring
spec:
  secretName: wildcard-k8s-vicio-ovh-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.k8s.vicio.ovh"
    - "k8s.vicio.ovh"
