apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAPoip+aQO2i2r8/CH5RNVsSQB9CylYdfoLv2k3YzaUPD1zEvF7E0FjjWy27wAXEw5et3h3yb10r0sM8RLwZ9oIeDNPHTwfxOgCqk3hAT3Of8Qg12CM68xVcKGkWBFpXnP3csZiNHHRPjGZYzjq9yjobaEHDXjYdMlB67dtRNOXeRdai8qWOfJSl73Gx/lWLZKyjrbfava3dIN6MxPXDU4w0M5HkVMLy5PMxYiA/08p/Xt8SXBASmoQvfnM5lVBlYS3ZHhid9Q3dW+FbsfUYkroZkDosB4cSK4K6TxXXY9oelauSU0NzV0MpXPEd9oJhxEB2VS7jpR/mwUECX1p/QjBmVi4ffpx6KCvwOiTpsVflLs4INRe7j7Gzf9qM38NOPlj3i1nACz+O9qoVjO4c6VW8mxFu3je3rnKqCEFoinrVRff+2xjzS5V42rsUU3Nt/PDkzRV5NGJiD31k9HiH5nxYNa87FiUF8H0T0gcvscCLu4gCvM/Z8jpBSGoL3TLhQt4DUhcxVH2dopsvsNZIDMaCEt3xPB/VndzYmsKW5NJZ+fAaQGDKwTNuy5mq6sfx+RgSN/3KUJY3PYnF9PYb6lTFkjK6rzOE3vjAY2M+/RgMKmwCOtlAe/7OLfkTVu9cHJ524Ni/oR1+kT0f42XYr8IQTmfPn9w3KRAdvMbeGqYveuDxHiL1lsVHEvDxhQz3+N1GG4rGMRH7Xf4w6uKQzHb5FoB5cD7uAeL4O4Ozw16Qg+oWloFZr5B
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: wiktor9196667@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-k8s-vicio-ovh
  namespace: monitoring
spec:
  secretName: wildcard-k8s-vicio-ovh-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.k8s.vicio.ovh"
    - "k8s.vicio.ovh"
