apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oncall
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: oncall
      targetRevision: 1.14.0
      helm:
        releaseName: oncall
        valueFiles:
          - $values/k8s/apps/oncall/values.yaml
    - repoURL: https://github.com/wiktorkowalski/k8s-hetzner.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: oncall
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
