oncall:
  base_url: https://oncall.k8s.vicio.ovh
  secrets:
    existingSecret: oncall-secrets
  grafana:
    url: https://grafana.k8s.vicio.ovh

database:
  type: postgresql
  postgresql:
    persistence:
      enabled: true
      storageClass: longhorn
      size: 10Gi

redis:
  enabled: true
  master:
    persistence:
      enabled: true
      storageClass: longhorn
      size: 5Gi

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

serviceMonitor:
  enabled: true
  labels:
    release: kube-prometheus-stack
