apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://twuni.github.io/docker-registry.helm
    chart: docker-registry
    targetRevision: 3.0.0
    helm:
      releaseName: registry
      valuesObject:
        proxy:
          enabled: true
          remoteurl: https://registry-1.docker.io
        persistence:
          enabled: true
          storageClass: longhorn
          size: 30Gi
        metrics:
          enabled: true
          port: 5001
          serviceMonitor:
            enabled: true
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: registry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
